version: 0.0
os: linux

files:
  - source: day-14/simple-python-app/
    destination: /app  # or wherever you want your app deployed on EC2
  - source: scripts/
    destination: /scripts  # optional if you just run from CodeDeploy directory

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
